server:
  port: 8085
  
spring: 
     profiles:
        active: dev 
        application:
            name: ClientApp 
            
management:
   endpoints:
          web:
            exposure:
              include: '*'   


  
  
  
  
     
      
  
   
